### ISSUE TITLE
Use of node_style() for gradient 

### ISSUE THREAD

**Issue by celions** [mrjoh3/cytoscape#10] opened 2020-09-24 08:27 UTC
Hi,

I want to know if there is support for applying color or size gradient. I've been trying with this code for the color gradient:
cytoscape(nodes = style_custom_nodes_reactive(), edges = style_edges_reactive()) %>%
        node_style(
          'background-fill' = 'radial-gradient',
          'background-gradient-stop-colors' = 'data(colors)',
          'background-gradient-stop-positions' = '25 75 80') %>%
        layout('breadthfirst', directed = TRUE) %>%
        panzoom()
But I wasn't able to observe any changes. 

Thanks,

Celia

**Comment by mrjoh3** [comment] 2020-11-05 08:13
apologies for the slow reply on this, 2020 has been a very odd year. Your code looks fine, I thin the issue is that this was only introduced for cytoscape version 3.3.0 and this package is using 3.2.12. 

see https://github.com/cytoscape/cytoscape.js/issues/2091

I will try and update to the latest version in the next week or so, hopefully then the gradients will work.

Matt

**Comment by mrjoh3** [comment] 2020-11-05 09:33
I have managed a quick first go. Have a look at branch https://github.com/mrjoh3/cytoscape/tree/update-to-3.16.3

after updating the following code worked for me

```
img_nodes <- data.frame(id = c('cat','bird','ladybug','aphid','rose','grasshopper','plant','wheat'),
                        images = c('https://farm2.staticflickr.com/1261/1413379559_412a540d29_b.jpg',
                                   'https://farm8.staticflickr.com/7272/7633179468_3e19e45a0c_b.jpg',
                                   'https://farm4.staticflickr.com/3063/2751740612_af11fb090b_b.jpg',
                                   'https://farm9.staticflickr.com/8316/8003798443_32d01257c8_b.jpg',
                                   'https://farm6.staticflickr.com/5109/5817854163_eaccd688f5_b.jpg',
                                   'https://farm7.staticflickr.com/6098/6224655456_f4c3c98589_b.jpg',
                                   'https://farm1.staticflickr.com/231/524893064_f49a4d1d10_z.jpg',
                                   'https://farm3.staticflickr.com/2660/3715569167_7e978e8319_b.jpg'),
                        stringsAsFactors = FALSE)
img_edges <- data.frame(source = c('cat','bird','bird','grasshopper','grasshopper','ladybug','aphid'),
                        target = c('bird','ladybug','grasshopper','plant','wheat','aphid','rose'),
                        stringsAsFactors = FALSE)

cytoscape(nodes = img_nodes,
          edges = img_edges) %>%
  layout(name = 'breadthfirst',
         directed = TRUE,
         padding = 10) %>%
  node_style("content" = "data(id)",
              "text-valign" = "center",
              "text-halign" = "center",
              'height' = 80,
              'width' = 80,
              "background-fill" = "radial-gradient",
              'background-fit' = 'cover',
              "background-gradient-stop-colors" = "cyan magenta yellow", 
              "background-gradient-stop-positions" = "25 75 80"
             ) 

```

**Comment by mrjoh3** [comment] 2020-11-05 09:34
let me know if this works for you and I will clean up the code and merge to master

**Comment by mrjoh3** [comment] 2020-11-08 09:12
update to 3.16.3 merged to master https://github.com/mrjoh3/cytoscape/commit/7bf7e5843bc54413c76f947a590221322f570438

**Closed as completed by mrjoh3** 2020-11-08 09:12 UTC
Labels: enhancement
